name: Test

on: [push, pull_request]

jobs:
  rust:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-targets
    - name: Check light-curve-dmdt/{README.md,example.png}
      working-directory: light-curve-dmdt
      run: |
        ./.ci/compose-readme.py
        git diff --word-diff --exit-code
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: Run code analysis
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-targets -- -D warnings

  arm:

    runs-on: [self-hosted, linux, ARM64]

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: cargo build --all-targets
