name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]

    steps:
    - uses: actions/checkout@v5
    - name: cargo-test
      run: cargo test --all-features --workspace

  fmt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: cargo-fmt
      run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: cargo-clippy
      run: cargo clippy --all-targets --all-features --workspace -- -D warnings

  readme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Check README.md and example.png
      run: |
        ./.ci/compose-readme.py
        git diff --word-diff --exit-code

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: cargo build
      run: cargo build --all-targets --all-features --workspace

  msrv-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Get minimum supported Rust version
        run: echo "::set-output name=msrv::$(grep '^rust-version = ' Cargo.toml | grep -o '[0-9.]\+')"
        id: get_msrv
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.get_msrv.outputs.msrv }}
      - name: Build
        run: cargo +${{ steps.get_msrv.outputs.msrv }} build --all-targets --all-features
